#!/bin/bash

set -e

# Determine PSMoveAPI root dir
PSMOVE_API_ROOT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/../../"

cd $PSMOVE_API_ROOT_DIR

echo "Installing prerequisites..."
sudo apt-get update -qq
sudo apt-get install -q -y  build-essential cmake 		\
		     	    libudev-dev libbluetooth-dev 	\
		     	    libv4l-dev libopencv-dev 		\
		     	    openjdk-7-jdk ant liblwjgl-java 	\
		     	    python-dev mono-mcs 		\
		     	    swig3.0 freeglut3-dev

# Configure
echo "Configuring build..."

mkdir -p build
cd build
if [ -z "$JAVA_HOME" ]; then
    echo "WARNING: \$JAVA_HOME is not set; please set it manually"
fi
export PATH=$PATH:$JAVA_HOME/bin
cmake $PSMOVEAPI_CMAKE_EXTRA_ARGS ..

# Build
echo "Building..."
make -j4

echo "Build completed successfully"
