#!/bin/bash

set -e

# Determine PSMoveAPI root dir
PSMOVE_API_ROOT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/../../"

cd $PSMOVE_API_ROOT_DIR

echo "Installing prerequisites..."
sudo apt-get update -qq
sudo apt-get install -q -y  build-essential cmake 		\
		     	    libudev-dev libbluetooth-dev 	\
		     	    libv4l-dev libopencv-dev 		\
		     	    openjdk-7-jdk ant liblwjgl-java 	\
		     	    python-dev mono-mcs 		\
		     	    swig3.0 freeglut3-dev

# Configure
echo "Configuring build..."

mkdir -p build
cd build
if [ -z "$JAVA_HOME" ]; then
    echo "WARNING: \$JAVA_HOME is not set; please set it manually"
fi
export PATH=$PATH:$JAVA_HOME/bin
cmake ..

# Build
echo "Building..."
make -j4

echo "Build completed successfully"

# Git revision identifier
PSMOVEAPI_REVISION=$(git describe --tags)

cd $PSMOVE_API_ROOT_DIR

DEST="psmoveapi-${PSMOVEAPI_REVISION}-linux"

mkdir -p "$DEST"
cp -rv \
    README COPYING \
    include \
    bindings/python \
    build/psmove \
    build/libpsmoveapi.so \
    build/libpsmoveapi_tracker.so \
    "$DEST"
rm -f "$DEST"/include/*.h.in
cp build/psmove_config.h "$DEST"/include/
mkdir -p upload
tar czvf upload/"$DEST".zip "$DEST"
rm -rf "$DEST"
