#!/bin/bash

set -e

# Determine PSMoveAPI root dir
PSMOVE_API_ROOT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/../../"

cd $PSMOVE_API_ROOT_DIR

if [ ! -d external/opencv ]; then
    echo "Cloning OpenCV 3.4..."
    git clone --depth 1 --branch 3.4 https://github.com/opencv/opencv.git external/opencv
else
    echo "Skipping OpenCV clone -- assuming it's checked out in external/opencv"
fi

# Configure
echo "Configuring build..."

mkdir -p build
cd build
if [ -z "$JAVA_HOME" ]; then
    echo "WARNING: \$JAVA_HOME is not set; please set it manually"
fi
export PATH=$PATH:$JAVA_HOME/bin
cmake ..

# Build
echo "Building..."
make -j4

echo "Build completed successfully"
