matrix:
  include:
    - os: linux
      dist: bionic
      sudo: required
      language: cpp
      compiler: clang
      env: BUILD_TYPE=linux-native-clang
    - os: linux
      dist: bionic
      sudo: required
      language: cpp
      compiler: gcc
      env: BUILD_TYPE=linux-cross-mingw64
    - os: linux
      dist: bionic
      sudo: required
      language: cpp
      compiler: gcc
      env: BUILD_TYPE=linux-cross-mingw32
    - os: osx
      osx_image: xcode8.1
      language: cpp
      compiler: clang
      env: BUILD_TYPE=macos-native-clang

deploy:
  provider: releases
  api_key:
    secure: JJqUUa2GqLYCswpro9s5zRFYC3G4G1Dy8XdyGqsnMkb5UCYuQZRjDWAEvdDFzsQ226bA8zHjl6qisqno9IrJq5xmRi5deqihEm9Z+iUIziTZwFk11dYl3UzA+7XnIufcbPYb3YvJymejtI53VGk2SaO8SCs9nvkQsGAxO1jkRpI=
  file: upload/*
  file_glob: true
  on:
    tags: true
  skip_cleanup: true

before_install:
  - bash -e -x scripts/install_dependencies.sh

install:
  - git submodule update --init --recursive
  - git fetch --tags
  - git fetch --unshallow || true

script:
  - bash -e -x scripts/build_package.sh
