#!/bin/bash -x -e
#
# Script to build Mac OS X binary snapshots of PS Move API
# Thomas Perl <m@thp.io>; 2012-09-28
#

# Determine PSMoveAPI root dir
if [[ "$TRAVIS" == "true" ]]
then
	export PSMOVEAPI_CHECKOUT=$TRAVIS_BUILD_DIR
else
	export PSMOVEAPI_CHECKOUT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/../../../"
fi

export OPENCV_CHECKOUT_DIR=$PSMOVEAPI_CHECKOUT/external/opencv
export OPENCV_BUILD_DIR=$PSMOVEAPI_CHECKOUT/external/opencv/build
export OPENCV_INSTALL_DIR=$OPENCV_CHECKOUT_DIR/build/install

# For parallel builds
MAKE_ARGS=-j4

# Take version from Debian package info (manual parsing...)
PSMOVEAPI_VERSION=$(grep -m 1 -o "psmoveapi (.*)" debian/changelog |
                    sed -e 's/psmoveapi (\(.*\))/\1/')

# Git revision identifier
PSMOVEAPI_REVISION=$(git describe --long --tags)

# By default, we build a snapshot. If "release" is the first argument, we
# build a release (do not add date and Git revision information to version)
if [ "$1" != "release" ]; then
    PSMOVEAPI_VERSION=${PSMOVEAPI_VERSION}~$(date +%F)+${PSMOVEAPI_REVISION}
fi

if [ ! -f $PSMOVEAPI_CHECKOUT/CMakeLists.txt ]; then
    echo "ERROR: You have to run this script in the PS Move API source root."
    exit 1
fi

# Build libusb-1.0 as universal static library
# needed for the PS3EYEDriver to access the PSEye
# otherwise we'd dynamically link against some the Homebrew libusb
(
    cd $PSMOVEAPI_CHECKOUT/external/libusb-1.0
    export ARCHFLAGS='-arch x86_64'
    export CFLAGS="$CFLAGS $ARCHFLAGS"
    export CXXFLAGS="$CXXFLAGS $ARCHFLAGS"
    ./autogen.sh
    ./configure
    make ${MAKE_ARGS}
)

cd $PSMOVEAPI_CHECKOUT

# Build OpenCV
if [ ! -d $OPENCV_INSTALL_DIR ]; then
    cd external
    if [ ! -d opencv ]; then
		git clone --depth 1 --branch 3.1.0 git://github.com/Itseez/opencv.git
    fi
    cd opencv
    rm -rf build
    mkdir -p build
    cd build
    cmake -DBUILD_SHARED_LIBS=OFF \
          -DBUILD_PERF_TESTS=OFF \
          -DBUILD_TESTS=OFF \
          -DBUILD_DOCS=OFF \
          -DBUILD_FAT_JAVA_LIB=OFF \
          -DBUILD_PACKAGE=OFF \
          -DBUILD_opencv_apps=OFF \
          -DBUILD_opencv_objdetect=OFF \
          -DBUILD_opencv_photo=OFF \
          -DBUILD_opencv_shape=OFF \
          -DBUILD_opencv_stitching=OFF \
          -DBUILD_opencv_superres=OFF \
          -DBUILD_opencv_ts=OFF \
          -DBUILD_opencv_video=OFF \
          -DBUILD_opencv_videostab=OFF \
          -DBUILD_opencv_world=OFF \
          -DBUILD_opencv_java=OFF \
          -DWITH_OPENEXR=OFF \
          -DWITH_FFMPEG=OFF \
          -DWITH_JASPER=OFF \
          -DWITH_TIFF=OFF \
          -DWITH_GPHOTO2=OFF \
          -DCMAKE_OSX_ARCHITECTURES="x86_64" \
          -DCMAKE_INSTALL_PREFIX=$(pwd)/install ..
    make ${MAKE_ARGS}
    make install
fi

cd $PSMOVEAPI_CHECKOUT

# Build PS Move API
PSMOVEAPI_PREFIX=/opt/psmoveapi_${PSMOVEAPI_VERSION}/
rm -rf build
mkdir build
cd build
cmake -DPSMOVE_USE_PS3EYE_DRIVER=ON \
      -DPSMOVE_BUILD_TRACKER=ON \
      -DPSMOVE_BUILD_JAVA_BINDINGS=ON \
      -DPSMOVE_BUILD_PROCESSING_BINDINGS=ON \
      -DOpenCV_DIR=${OPENCV_BUILD_DIR} \
      -DCMAKE_INSTALL_PREFIX=$PSMOVEAPI_PREFIX ..
make ${MAKE_ARGS}

# Don't package on CI server; it doesn't have enough memory/disk space and fails
if [[ "$TRAVIS" != "true" ]]
then
	mkdir tmp
	DESTDIR=$(pwd)/tmp make install

	cd $PSMOVEAPI_CHECKOUT

	# Packaging
	rm -rf dist
	mkdir -p dist
	echo $PSMOVEAPI_REVISION >dist/revision.txt
	cp -rpv build/tmp/* dist/

	cd $PSMOVEAPI_CHECKOUT

	# Tar it up
	PACKAGE_NAME=psmoveapi_${PSMOVEAPI_VERSION}_osx108
	rm -rf $PACKAGE_NAME
	mv dist $PACKAGE_NAME
	mkdir -p upload
	tar czvf upload/${PACKAGE_NAME}.tgz $PACKAGE_NAME
	rm -rf $PACKAGE_NAME

	# Copy the Processing bindings
	cp build/psmove_processing_macosx.zip upload/${PACKAGE_NAME}_processing.zip
else
	echo "Skipping package step because this is a CI server"
fi

