#!/bin/bash -xe
#
# Script to cross compile PS Move API for Windows on a Linux host
# Thomas Perl <m@thp.io>; 2012-09-27
#
# Dependencies (Ubuntu/Debian):
#
#     sudo apt-get install mingw-w64 g++-mingw-w64
#

export PSMOVEAPI_CHECKOUT=$(pwd)

if [ ! -f $PSMOVEAPI_CHECKOUT/CMakeLists.txt ]; then
    echo "ERROR: You have to run this script in the PS Move API source root."
    exit 1
fi

OPENCV_VERSION=3.1.0
PSMOVEAPI_VERSION=$(git describe --tags)

MAKE_ARGS="$@"

for PSMOVEAPI_PLATFORM in i686-w64-mingw32 x86_64-w64-mingw32; do
    export TOOLCHAIN=$PSMOVEAPI_CHECKOUT/cmake/${PSMOVEAPI_PLATFORM}.toolchain
    export OPENCV_CHECKOUT_DIR=$PSMOVEAPI_CHECKOUT/external/opencv
    export OPENCV_BUILD_DIR=$OPENCV_CHECKOUT_DIR/build-${PSMOVEAPI_PLATFORM}

    # Build OpenCV
    if [ ! -d $OPENCV_BUILD_DIR ]; then
        if [ ! -d external/opencv ]; then
            if [ ! -f ${OPENCV_VERSION}.zip ]; then
                curl -O https://github.com/Itseez/opencv/archive/${OPENCV_VERSION}.zip
            fi
            unzip ${OPENCV_VERSION}.zip
            mv opencv-${OPENCV_VERSION} external/opencv
        fi
        cd external/opencv
        rm -rf ${OPENCV_BUILD_DIR}
        mkdir -p ${OPENCV_BUILD_DIR}
        cd ${OPENCV_BUILD_DIR}
        cmake -DCMAKE_TOOLCHAIN_FILE=$TOOLCHAIN \
              -DBUILD_SHARED_LIBS=OFF \
              -DBUILD_PERF_TESTS=OFF \
              -DBUILD_TESTS=OFF \
              -DBUILD_DOCS=OFF \
              -DBUILD_opencv_flann=OFF \
              -DBUILD_opencv_features2d=OFF \
              -DBUILD_opencv_objdetect=OFF \
              -DBUILD_opencv_photo=OFF \
              -DBUILD_opencv_ts=OFF \
              -DBUILD_opencv_ml=OFF \
              -DBUILD_opencv_video=OFF \
              -DWITH_OPENEXR=OFF \
              -DWITH_FFMPEG=OFF \
              -DWITH_JASPER=OFF \
              -DWITH_TIFF=OFF \
              ${OPENCV_CHECKOUT_DIR}
        make ${MAKE_ARGS}
    fi

    cd $PSMOVEAPI_CHECKOUT

    # Build PS Move API
    rm -rf build
    mkdir build
    cd build
    cmake -DPSMOVE_BUILD_TRACKER=ON \
          -DOpenCV_DIR=${OPENCV_BUILD_DIR} \
          -DCMAKE_TOOLCHAIN_FILE=$TOOLCHAIN \
          ${PSMOVEAPI_CHECKOUT}
    make ${MAKE_ARGS}

    cd $PSMOVEAPI_CHECKOUT

    # Packaging
    rm -rf dist
    mkdir -p dist/bin
    cp README COPYING dist/
    cp -r docs dist/
    cp build/*.exe dist/bin/
    cp build/libpsmoveapi.dll dist/bin/
    cp build/libpsmoveapi_tracker.dll dist/bin/
    mkdir -p dist/include
    cp include/*.h dist/include/

    cd $PSMOVEAPI_CHECKOUT

    # Zip it up
    PACKAGE_NAME=psmoveapi-${PSMOVEAPI_VERSION}-${PSMOVEAPI_PLATFORM}
    rm -rf $PACKAGE_NAME
    mv dist $PACKAGE_NAME
    mkdir -p upload
    zip -r upload/${PACKAGE_NAME}.zip $PACKAGE_NAME
    rm -rf $PACKAGE_NAME
done
